config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :searches, :reply_tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    searches_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/reply_tweets_controller.rb
class ReplyTweetsController < ApplicationController

  def index
    # grab all tweets
    @searches = Search.where(replied: [false, nil]).all
    # puts @searches
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "qAdOydT3JrhsQbQSKvf69TV6P"
      config.consumer_secret     = "XEZGASLs9lQ9J5IgzWqFoNpoUaifv1PqNxJQM8FHjPSXdkewZW"
      config.access_token        = "105933959-rvPjo0oPEKfPXk5kP1d1v94Jdxp7ykvFMpqu2Sj0"
      config.access_token_secret = "AnrbAqcTze22tc2t0VrWFSdzg89RS5emrz9QvBC37nm3V"
    end
    @searches.each do |search|
      search_tweets(search.search_text,client)
    end

  end

  def search_tweets(text,client)
    puts text
    client.search(text, result_type: "recent").take(3).each do |tweet|
      puts tweet.text
      puts " Twitter Id: #{tweet.id}"
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @searches = Search.all
  end

  def show
  end

  def new
    @search = current_user.searches.build
  end

  def edit
  end

  def create
    @search = current_user.searches.build(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_search
      @search = Search.find(params[:id])
    end

    def search_params
      params.require(:search).permit(:name, :search_text, :reply_tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reply_tweets_helper.rb
module ReplyTweetsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/index.html.erb
    <!--Carousel Wrapper-->
    <div id="video-carousel-example2" class="carousel slide carousel-fade" data-ride="carousel">
        <!--Indicators-->
        <ol class="carousel-indicators">
            <li data-target="#video-carousel-example2" data-slide-to="0" class="active"></li>
            <li data-target="#video-carousel-example2" data-slide-to="1"></li>
            <li data-target="#video-carousel-example2" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->

        <!--Slides-->
        <div class="carousel-inner" role="listbox">
            <!--First slide-->
            <div class="carousel-item active">
                <!--Mask color-->
                <div class="view hm-black-light">

                    <!--Video source-->
                    <video class="video-full" autoplay loop>
                        <source src="http://jibrilsulaiman.com/wp-content/uploads/2017/05/twitter.mp4" type="video/mp4" />
                    </video>
                    <div class="full-bg-img"></div>
                </div>

                <!--Caption-->
                <div class="carousel-caption">
                    <div class="flex-center animated fadeIn">
                        <ul>
                            <li>
                                <h1 class="h1-responsive">Tweetp.ly</h1></li>
                            <li>
                                <p>Auto Reply to User Tweets Based on Predefined Searches</p>
                            </li>
                            <li>
                                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
                                <a target="_blank" href="http://jibrilsulaiman.com" class="btn btn-default btn-lg" rel="nofollow">Learn more</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!--Caption-->
            </div>
            <!--/First slide-->

            <!--Second slide-->
<!--             <div class="carousel-item">
 -->                <!--Mask color-->
<!--                 <div class="view hm-black-light">
 -->                    <!--Video source-->
                  <!--   <video class="video-full" autoplay loop>
                        <source src="http://mdbootstrap.com/images/video/Sail-Away.mp4" type="video/mp4" />
                    </video>
                    <div class="mask"></div>
                </div> -->

                <!--Caption-->
                <!-- <div class="carousel-caption">
                    <div class="flex-center animated fadeInDown">
                        <ul>
                            <li>
                                <h1 class="h1-responsive">Lots of tutorials at your disposal</h1>
                            </li>
                            <li>
                                <p>And all of them are FREE!</p>
                            </li>
                            <li>
                                <a target="_blank" href="http://mdbootstrap.com/bootstrap-tutorial/" class="btn btn-primary btn-lg" rel="nofollow">Start learning</a>
                            </li>
                        </ul>
                    </div>
                </div> -->
                <!--/.Caption-->
           <!--  </div> -->
            <!--/Second slide-->

            <!--Third slide-->
    <!--         <div class="carousel-item">
                <!--Mask color-->
           <!--      <div class="view hm-black-strong">
                    <!--Video source-->
                  <!--   <video class="video-full" autoplay loop>
                        <source src="http://mdbootstrap.com/images/video/Agua-natural.mp4" type="video/mp4" />
                    </video>
                    <div class="mask"></div>
                </div>  -->

                <!--Caption-->
<!--                 <div class="carousel-caption">
                    <div class="flex-center animated fadeInDown">
                        <ul>
                            <li>
                                <h1 class="h1-responsive">Visit our support forum</h1></li>
                            <li>
                                <p>Our community can help you with any question</p>
                            </li>
                            <li>
                                <a target="_blank" href="http://mdbootstrap.com/forums/forum/support/" class="btn btn-default btn-lg" rel="nofollow">Support forum</a>
                            </li>
                        </ul>
                    </div>
                </div> -->
                <!--/.Caption-->
            </div>
            <!--/Third slide-->
        </div>
        <!--/.Slides-->

    </div>
    <!--/.Carousel Wrapper-->

    <!--/.Main layout-->





    <!-- SCRIPTS -->

app/views/layouts/_footer.html.erb
 <!--Footer-->
    <footer class="page-footer center-on-small-only footer">

        <!--Footer Links-->
        <div class="container-fluid">
            <div class="row">

                <!--First column-->
                <div class="col-lg-3 offset-lg-1 hidden-lg-down">
                    <h5 class="title">ABOUT TWEETP.LY</h5>
                </div>
                <!--/.First column-->

                <hr class="hidden-md-up">

                <!--Second column-->
                <div class="col-lg-2 col-md-4 offset-lg-1">
                    <h5 class="title"><a href="http://jibrilsulaiman.com">Contact Us</a></h5>
                </div>
                <!--/.Second column-->

                <hr class="hidden-md-up">

                <!--Third column-->
                <div class="col-lg-2 col-md-4">
                    <h5 class="title"><a href="http://jibrilsulaiman.com">Log In</a></li></h5>
                </div>
                <!--/.Third column-->

                <hr class="hidden-md-up">

                <!--Fourth column-->
                <div class="col-lg-2 col-md-4">
                    <h5 class="title"><a href="http://jibrilsulaiman.com">Privacy</a></h5>
                </div>
                <!--/.Fourth column-->

            </div>
        </div>
        <!--/.Footer Links-->

        <hr>

        <!--Call to action-->
        <div class="call-to-action">

            <ul>
                <li>
                    <h5>Start Tweeting Replies Based on Search Results</h5></li>
                <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger" %></li>
                <li><a target="_blank" href="http://jibrilsulaiman.com" class="btn btn-default" rel="nofollow">Learn more</a></li>
            </ul>
        </div>
        <!--/.Call to action-->

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2017 Copyright: <a href="http://jibrilsulaiman.com"> WDI Project 5 </a>

            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

app/views/layouts/_header.html.erb
     <!--Navbar-->
    <nav class="navbar navbar-toggleable-md navbar-dark fixed-top scrolling-navbar">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div><%= link_to image_tag("tweetply.png", :size => "138x65"), root_path,class: "brand-logo"  %></div>

            <div class="collapse navbar-collapse" id="navbarNav1">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <%= link_to "Home", root_path, class: "nav-link" %>
                    </li>
                    <% if user_signed_in? %>
                      <li class="nav-item nav-link"><%= link_to "New Tweetply", new_search_path, class: "" %></li>
                      <li class="nav-item nav-link"><%= link_to "Dash", searches_path, class: "" %></li>
                      <li class="nav-item nav-link"><%= link_to "Profile", edit_user_registration_path, class: "" %></li>
                      <li class="nav-item nav-link"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>


                    <% else %>
                      <li class="nav-item nav-link"><%= link_to "Sign Up", new_user_registration_path, class: "" %></li>
                     <li class="nav-item nav-link"><%= link_to "Log In", new_user_session_path, class: "" %></li>
                      <li class="nav-item nav-link">
                        <a class="">Features</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="">Pricing</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="">About</a>
                    </li>
                    <% end %>

                </ul>

            </div>
        </div>
    </nav>
    <!--/.Navbar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetp.ly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'arrow.png', sizes: '16x16 32x32' %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Material Design Bootstrap -->


  </head>

  <body>

  <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <%= yield %>
<%= render 'layouts/footer' %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
  </body>
</html>

app/views/reply_tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twitter Searches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Search text</th>
      <th>Tweetp.ly</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.name %></td>
        <td><%= search.search_text %></td>
        <td><%= search.reply_tweet %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/_form.html.erb
<%= form_for(search) do |f| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :search_text %>
    <%= f.text_field :search_text %>
  </div>

  <div class="field">
    <%= f.label :reply_tweet %>
    <%= f.text_field :reply_tweet %>
  </div>

  <div class="actions">
  <ul>
  <li>
    <%= f.submit :create, class: 'btn btn-primary' %>
      </li>
      <li>
      <%= link_to 'Back', searches_path, class: "btn btn-default"  %>
      </li>

    </ul>
  </div>
<% end %>

app/views/searches/edit.html.erb
<div class="container partials">

<h3>Editing Search</h3>

<%= render 'form', search: @search %>
<ul>
<li><%= link_to 'Show', @search %> </li>
<li><%= link_to 'Back', searches_path %></li>
</ul>

</div>

app/views/searches/index.html.erb
<div class="container partials">

<p id="notice"><%= notice %></p>

<h3>Tweetp.ly's</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Search text</th>
      <th>Tweetp.ly</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.name %></td>
        <td><%= search.search_text %></td>
        <td><%= search.reply_tweet %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path, class: "btn btn-default" %>
</div>

app/views/searches/new.html.erb
<div class="container partials">

<h3>New Tweetp.ly</h3>

<%= render 'form', search: @search %>


</div>

app/views/searches/show.html.erb
<div class="container partials">

<div class="row">
  <p>
    <strong>Name:</strong>
    <%= @search.name %>
  </p>

  <p>
    <strong>Search text:</strong>
    <%= @search.search_text %>
  </p>

  <p>
    <strong>Reply tweet:</strong>
    <%= @search.reply_tweet %>
  </p>
</div>

<div class="row">

<!--  -->

</div>



<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

</div>